POST http://localhost:3000/api/validate-purchase HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
	"platform": "ANDROID",
	"receipt": {
		"packageName": "your.package.name",
		"productId": "your_product_id",
		"purchaseToken": "your_purchase_token",
		"subscription": true //"if subscription true else false"
	}
}